# in test don't use yet

name: end-2-end build

on:
  workflow_dispatch:
  
permissions:
  contents: read
  pull-requests: read
  actions: read
  security-events: write
  packages: write

concurrency:
  group: ci-e2e-${{ github.ref }}-1
  cancel-in-progress: true

jobs:
  call-golangci-lint:
    uses: ./.github/workflows/_gocilint.yml
  
  call-gosec-scanning:
    uses: ./.github/workflows/_gosecscan.yml
    needs: call-golangci-lint
    
  call-docker-build:
    uses: ./.github/workflows/_docker-build.yml
    needs: call-gosec-scanning
