# in test don't use yet

name: end-2-end build

on:
  workflow_dispatch:
  
permissions:
  contents: read
  pull-requests: read

concurrency:
  group: ci-e2e-${{ github.ref }}-1
  cancel-in-progress: true

jobs:
  call-golangci-lint:
    uses: ondat/trousseau/.github/workflows/go-lint-pull_request.yaml
  
  call-gosec-scanning:
    uses: ondat/trousseau/.github/workflows/gosec-scanner-on-pull_request.yaml
    needs: call-golangci-lint
    
  call-codeql-analysis:
    uses: ondat/trousseau/.github/workflows/codeql-analysis.yml
    needs: call-gosec-scanning
